### ISSUE TITLE
Comment for manual

### ISSUE THREAD

**Issue by ali-mahdavi-mazdeh** [psu-efd/pyHMT2D#2]
I could not run "process_RAS_2D_Data.py" for a new project that defined by myself. when it tried to open HEC-RAS results it gave me this error: "Unable to open object (object 'Node X Vel' doesn't exist)".

I found that when we want to run the HEC-RAS we need to check the box "writ the velocity data at face node locations in 2D meshes" in the output control option of HEC-RAS. like the following image.

![image](https://user-images.githubusercontent.com/83440730/118516673-88ee4180-b704-11eb-9ca6-76852abce460.png)

**Comment by psu-efd** [comment]
Thanks for your note. I will add this to the user manual.
