### ISSUE TITLE
Installation procedure in the documentation - suggestions

### ISSUE THREAD

**Issue by jmp75** [psu-efd/pyHMT2D#3]
Thank you for your work.

I have a couple of suggestions for the manual, in the installation section.

I first tried to install some dependency packages from conda-forge, but when installing the additional packages from pypi this did not go well notably with VTK versions clashes. I suggest  to emphasize in the documentation that installing using pip is preferred.

Also I don't this it is necessary to install vtk upfront, which currently installs vtk-9.0.1 but then pyHMT2D will overwrite this with vtk-8.2 when installed, as it is declared in the setup.py file. 

The following set of instructions ended up letting me install pyHMT2D

```sh
conda create -n py37 python=3.7
conda activate py37
pip install h5py
pip install pywin32
pip install affine
pip install "C:\Users\xxxyyy\Downloads\GDAL-3.3.0-cp37-cp37m-win_amd64.whl"
```

I was not sure why the documentation suggested  the --user option in `pip install GDAL-3.3.0-cp37-cp37m-win_amd64.whl --user`, at least if using virtualenv or a conda environment. In my experience installing user-level packages can cause grief in other contexts (as I think it overrides versions in any virtual environment).

Also to run the first "backwater" example, it appears there is a dependency in the package that is not listed, meshio.

```sh
pip install meshio
```

**Comment by jmp75** [comment]
Perhaps a requirements.txt and/or conda yaml file(s) with locked versions for dependencies would help streamline the installation process.

**Comment by psu-efd** [comment]
> 
> 
> Thank you for your work.
> 
> I have a couple of suggestions for the manual, in the installation section.
> 
> I first tried to install some dependency packages from conda-forge, but when installing the additional packages from pypi this did not go well notably with VTK versions clashes. I suggest to emphasize in the documentation that installing using pip is preferred.
> 

Yes, I updated the user manual to emphasize the use of pip.

> Also I don't this it is necessary to install vtk upfront, which currently installs vtk-9.0.1 but then pyHMT2D will overwrite this with vtk-8.2 when installed, as it is declared in the setup.py file.
> 

VTK is at the core of pyHMT2D. It serves as the common data format for different models. So it is necessary to install vtk upfront. We encountered the same version conflict before. Currently only vtk v8.2 works (it seems versions >9 have changed several function call interfaces). If necessary, we will upgrade pyHMT2D's vtk dependency to version > 9. 

> The following set of instructions ended up letting me install pyHMT2D
> 
> ```shell
> conda create -n py37 python=3.7
> conda activate py37
> pip install h5py
> pip install pywin32
> pip install affine
> pip install "C:\Users\xxxyyy\Downloads\GDAL-3.3.0-cp37-cp37m-win_amd64.whl"
> ```
> 

Thanks for sharing your command script. Others can try. 

> I was not sure why the documentation suggested the --user option in `pip install GDAL-3.3.0-cp37-cp37m-win_amd64.whl --user`, at least if using virtualenv or a conda environment. In my experience installing user-level packages can cause grief in other contexts (as I think it overrides versions in any virtual environment).

Not sure why I put the "--user" option there. Maybe because of version conflict. Anyway, I have removed the option in the user manual. 

> Also to run the first "backwater" example, it appears there is a dependency in the package that is not listed, meshio.
> 
> ```shell
> pip install meshio
> ```

In the "setup.py" file, I have moved the "meshio" package from optional to required list. Thanks.

**Comment by mdbartos** [comment]
Greetings, 

Regarding installation, are there plans to support Python versions other than 3.7? This seems a bit restrictive if the software is intended for a broad audience.

If there are only plans to support Python 3.7, I would recommend making this clear in the README. I'd also recommend discussing how to install the software within a virtual environment like pyenv, as a large number of users will be using different versions of Python.

Best,
MDB

**Comment by psu-efd** [comment]
> 
> 
> Greetings,
> 
> Regarding installation, are there plans to support Python versions other than 3.7? This seems a bit restrictive if the software is intended for a broad audience.
> 
> If there are only plans to support Python 3.7, I would recommend making this clear in the README. I'd also recommend discussing how to install the software within a virtual environment like pyenv, as a large number of users will be using different versions of Python.
> 
> Best,
> MDB

As of now, I have only fully tested Python 3.7. Other versions may also work (may need some tweaks). One reason that other versions of Python may have problem is that pyHMT2D uses several packages, such as VTK, which require certain version of Python. In addition, these dependent packages changes from version to version. Some of them change calling interface if I change version. Regardless, if you try other versions of Python and dependent packages, please let me know whether they work.

**Comment by psu-efd** [comment]
> 
> 
> Greetings,
> 
> Regarding installation, are there plans to support Python versions other than 3.7? This seems a bit restrictive if the software is intended for a broad audience.
> 
> If there are only plans to support Python 3.7, I would recommend making this clear in the README. I'd also recommend discussing how to install the software within a virtual environment like pyenv, as a large number of users will be using different versions of Python.
> 
> Best,
> MDB

Sorry I forgot to reply to you about the virtual environment question. Yes, indeed I have a full section in the User Manual about how to setup the Python Virtual Environment, see Section 2.1 and Appendix A. Thanks.
