### ISSUE TITLE
Version 6.3.1 bug

### ISSUE THREAD

**Issue by erakhmatulina** [psu-efd/pyHMT2D#6]
To make version 6.3.1 work, need to add:

elif (self.getVersion() == '6.3.1'):
            self._RASController = win32.gencache.EnsureDispatch('RAS631.HECRASController')

to

https://github.com/psu-efd/pyHMT2D/blob/16e6ac5c074fd394b78091a6dfc6d280dc451680/pyHMT2D/Hydraulic_Models_Data/RAS_2D/HEC_RAS_Model.py#L287

**Comment by psuliuxf** [comment]
Added.
