### ISSUE TITLE
HEC-RAS Basics, Result Format, I/O not in User Manual

### ISSUE THREAD

**Issue by pmd84** [psu-efd/pyHMT2D#7]
Hello, 
I just downloaded the pyHMT2D user manual and have read through it. There is a sections in the table of contents titled "HEC-RAS Basics, Result Format, and I/O", containing important sub-sections regarding running and extracting results from HEC-RAS 2D models. Within the PDF, these sections are not present. Clicking on their heading within the table of contents just sends me to the top of the PDF.  Could you please re-upload the PDF to the Docs including these sections of the user manual? Thank you.

**Comment by psu-efd** [comment]
The User Manual has been updated to include the information you requested. However, the newly added chapters on the data structure and result format for HEC-RAS and SRH-2D are not complete. HEC seems also to change the format from version to version.

**Comment by pmd84** [comment]
Thank you, Professor Liu. Even though the sections are considered incomplete, they are immensely informative.
